
import type { Product } from './types';
import { placeholderImages } from './placeholder-images.json';

const getImageUrl = (id: string) => placeholderImages.find(p => p.id === id)?.imageUrl || '';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Rapid Pain Relief',
    description: 'Provides effective relief from pain, inflammation, and fever. Ideal for headaches, dental pain, and menstrual cramps.',
    price: 7.50,
    imageUrl: getImageUrl('prod_001'),
    category: 'Pain Relief',
    dosage: 'Take 1-2 tablets every 4-6 hours as needed. Do not exceed 6 tablets in 24 hours.',
    stock: 150,
  },
  {
    id: 'prod_002',
    name: 'Immunity Booster C+',
    description: 'A high-potency Vitamin C supplement to support immune system function and provide antioxidant protection.',
    price: 15.00,
    imageUrl: getImageUrl('prod_002'),
    category: 'Vitamins & Supplements',
    dosage: 'Take 1 tablet daily with a meal.',
    stock: 200,
  },
  {
    id: 'prod_003',
    name: 'Cold & Flu Relief',
    description: 'Multi-symptom relief from common cold and flu symptoms including cough, congestion, sore throat, and fever.',
    price: 9.99,
    imageUrl: getImageUrl('prod_003'),
    category: 'Cold & Flu',
    dosage: 'Take 2 caplets every 4 hours. Do not exceed 8 caplets in 24 hours.',
    stock: 80,
  },
  {
    id: 'prod_004',
    name: 'Allergy Relief Tablets',
    description: '24-hour non-drowsy relief from indoor and outdoor allergy symptoms like sneezing, runny nose, and itchy eyes.',
    price: 18.99,
    imageUrl: getImageUrl('prod_004'),
    category: 'Allergy',
    dosage: 'Take 1 tablet daily. Not for children under 6 years.',
    stock: 120,
  },
  {
    id: 'prod_005',
    name: 'Calcium + Vitamin D3',
    description: 'Supports strong bones and teeth. Vitamin D3 helps improve calcium absorption.',
    price: 15.79,
    imageUrl: getImageUrl('prod_005'),
    category: 'Vitamins & Supplements',
    dosage: 'Take 2 tablets daily, preferably with a meal.',
    stock: 95,
  },
  {
    id: 'prod_006',
    name: 'Paracetamol 500mg',
    description: 'Gentle pain and fever reducer. Suitable for a wide range of pains including headaches and muscle aches.',
    price: 4.50,
    imageUrl: getImageUrl('prod_006'),
    category: 'Pain Relief',
    dosage: 'Take 1-2 tablets every 4-6 hours. Maximum 8 tablets in 24 hours.',
    stock: 300,
  },
  {
    id: 'prod_007',
    name: 'Probiotic Daily Support',
    description: 'Helps maintain a healthy digestive balance and supports immune health with 10 billion live cultures.',
    price: 25.00,
    imageUrl: getImageUrl('prod_007'),
    category: 'Digestive Health',
    dosage: 'Take 1 capsule daily.',
    stock: 60,
  },
  {
    id: 'prod_008',
    name: 'Melatonin 5mg',
    description: 'A natural sleep aid to help you fall asleep faster and improve sleep quality. Non-habit forming.',
    price: 11.29,
    imageUrl: getImageUrl('prod_008'),
    category: 'Vitamins & Supplements',
    dosage: 'Take 1 tablet 30 minutes before bedtime.',
    stock: 110,
  },
];
